In [5]:
import tensorflow as tf
import tensorflow as tf
x=tf.constant([2.0,4.0,6.0,8.0],shape=[1,4],name='x')
y=tf.constant([5.0,6.0,7.0,8.0],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        x1=tf.reduce_mean(x)
        y1=tf.reduce_mean(y)
        sess=tf.Session()
    print("mean of x is",sess.run(x1))
    print("mean of y is",sess.run(y1))

mean of x is 5.0
mean of y is 6.5


In [6]:
with tf.name_scope("variance"):
    with tf.name_scope("scope_sub1"):
        a=tf.subtract(x,x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_sub2"):
        b=tf.subtract(y,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_square"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
    print("the variance is",sess4.run(var))

[[-3. -1.  1.  3.]]
[[-1.5 -0.5  0.5  1.5]]
[[ 9.  1.  1.  9.]]
the variance is 20.0


In [7]:
with tf.name_scope("covariance"):
    with tf.name_scope("multiplication"):
        mul1=tf.multiply(a,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print("the covariance is",sess6.run(covar))

[[ 4.5  0.5  0.5  4.5]]
the covariance is 10.0


In [8]:
with tf.name_scope("value_of_c"):
    c=tf.divide(covar,var)
print("the value of c is",sess.run(c))
with tf.name_scope("value_of_m"):
    with tf.name_scope("multiplication2"):
        mul2=tf.multiply(c,x1)
    print(sess.run(mul2))
    with tf.name_scope("subtract"):
        sub=tf.subtract(y1,mul2)
    print("the value of c is",sess.run(sub))

the value of c is 0.5
2.5
the value of c is 4.0


In [9]:

with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/Assignment22", sess.graph)
    writer.close()